repack step 1
tduretz/ExactFieldSolutions.jl pull request #4
Opened 2024-09-20 11:09 UTC by tduretz

* allow for tuples as input and name tuples as output
* create specific environment for example
* remove Plots, SparseDiffTools and Symbolics from dips
* update function docs: default parameters are stated + tuple call examples
* update README.md

2024-09-20 13:01 UTC, albert-de-montserrat commented on src/Diffusion1D/Diffusion1D_Gaussian.jl
> +function Diffusion1D_Gaussian(coords::Tuple;
Does this work for `NamedTuple`s? 

```julia-repl
julia> a=(;x=1, y=2)
(x = 1, y = 2)

julia> typeof(a) isa Tuple
false

julia> typeof(a) <: Tuple
false
```

2024-09-20 13:09 UTC, tduretz commented on src/Diffusion1D/Diffusion1D_Gaussian.jl
> +function Diffusion1D_Gaussian(coords::Tuple;
thanks a lot for suggesting the change to `::Union{Tuple, NamedTuple}` !

2024-09-23 07:59 UTC, albert-de-montserrat requested changes

2024-09-23 07:59 UTC, albert-de-montserrat commented on examples/benchmarks/ExamplePoisson1D.jl
> +function main(ncx, method)
```suggestion
@views function main(ncx, method) 
```

2024-09-23 07:59 UTC, albert-de-montserrat commented on examples/benchmarks/ExamplePoisson1D.jl
> +    if method==:Spotz         # Discretisation of Spotz et al., 1995
```suggestion
    if method===:Spotz         # Discretisation of Spotz et al., 1995
```

2024-09-23 07:59 UTC, albert-de-montserrat commented on examples/benchmarks/ExamplePoisson1D.jl
> +    elseif method==:Abide # Discretisation of Abide et al., 2020
```suggestion
    elseif method===:Abide # Discretisation of Abide et al., 2020
```

2024-09-23 20:21 UTC, luraess commented
LGTM - do not have time to test it, but thanks for incorporating these new changes!

2024-09-23 20:21 UTC, luraess approved these changes
LGTM

2024-09-24 07:37 UTC, tduretz commented
@JuliaRegistrator register

2024-09-24 07:37 UTC, JuliaRegistrator commented
Comments on pull requests will not trigger Registrator, as it is disabled. Please try commenting on a commit or issue.

2024-09-24 07:38 UTC, merged